version: '3.9'
services:
  app:
    build:
      context: .
      shm_size: '5gb'


    # dockerfile: Dockerfile
    container_name: 'company_analysis'
    # devices:
    #   - /dev/nvidia0
    working_dir: '/workspace'
    volumes:
      -  ./:/workspace/
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ports:
      - "127.0.0.1:8081:8889"
    tty: true
    ipc: host
